AWSTemplateFormatVersion: "2010-09-09"

# This template deploys a VPC, with a pair of public and private subnets spread
# across two Availability Zones. It deploys an Internet Gateway, with a default
# route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ),
# and default routes for them in the private subnets.
Description: >
  This template deploys a basic VPC with nothing in it.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  CIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref EnvironmentName, "vpc"]]

Outputs:
  vpcId:
    Description: The ID used to refer to the created VPC
    Value: !Ref VPC
