Description:
  This template deploys a VPC, with a pair of public and private subnets spread
  across two Availability Zones. It deploys an internet gateway, with a default
  route on the public subnets. It deploys a pair of NAT gateways (one in each AZ),
  and default routes for them in the private subnets.

Parameters:
  TemplateBucketURL:
    Description: The URL where the CloudFormation templates are hosted.
    Type: String
    Default: https://s3.amazonaws.com/recright-sandbox-cloudformation

  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    AllowedValues: ["development", "staging", "production"]

Mappings:
  TemplateLocations:
    Infrastructure:
      vpcPath: "infrastructure/vpc.yaml"
  Environments:
    development: # demo
      vpcCIDR: 172.22.0.0/16
      publicSubnet1CIDR: 172.22.8.0/21
      publicSubnet2CIDR: 172.22.16.0/21
      privateSubnet1CIDR: 172.22.32.0/21
      privateSubnet2CIDR: 172.22.40.0/21
    staging:
      vpcCIDR: 172.21.0.0/16
      publicSubnet1CIDR: 172.21.8.0/21
      publicSubnet2CIDR: 172.21.16.0/21
      privateSubnet1CIDR: 172.21.24.0/21
      privateSubnet2CIDR: 172.21.32.0/21
    production:
      vpcCIDR: 172.23.0.0/16
      publicSubnet1CIDR: 172.23.8.0/21
      publicSubnet2CIDR: 172.23.16.0/21
      publicSubnet3CIDR: 172.23.24.0/21
      privateSubnet1CIDR: 172.23.32.0/21
      privateSubnet2CIDR: 172.23.40.0/21
      privateSubnet3CIDR: 172.23.48.0/21

Conditions:
  # isInDevelopment: !Equals [!Ref EnvironmentName, development]
  # isInStaging: !Equals [!Ref EnvironmentName, staging]
  isInProduction: !Equals [!Ref EnvironmentName, production]

Resources:
  VPC: # Ignore warning on VPC
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Join
        - "/"
        - - !Ref TemplateBucketURL
          - !FindInMap [TemplateLocations, Infrastructure, vpcPath]
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        TemplateBucketURL: !Ref TemplateBucketURL
        VpcCIDR: !FindInMap [Environments, !Ref EnvironmentName, vpcCIDR]
        PublicSubnet1CIDR:
          !FindInMap [Environments, !Ref EnvironmentName, publicSubnet1CIDR]
        PublicSubnet2CIDR:
          !FindInMap [Environments, !Ref EnvironmentName, publicSubnet2CIDR]
        PublicSubnet3CIDR: !If
          - isInProduction
          - !FindInMap [Environments, !Ref EnvironmentName, publicSubnet3CIDR]
          - ""
        PrivateSubnet1CIDR:
          !FindInMap [Environments, !Ref EnvironmentName, privateSubnet1CIDR]
        PrivateSubnet2CIDR:
          !FindInMap [Environments, !Ref EnvironmentName, privateSubnet2CIDR]
        PrivateSubnet3CIDR: !If
          - isInProduction
          - !FindInMap [Environments, !Ref EnvironmentName, privateSubnet3CIDR]
          - ""
